---
# Source: demoapp/charts/ui/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
  labels:
    helm.sh/chart: ui-0.1.0
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: demoapp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  PORT: "80"
